---
spring:

  zipkin:
    endpoint: http://localhost:9411
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317
  otel:
    exporter:
      otlp:
        endpoint: http://localhost:4317
  cloud:
    function:
      definition: myService
    stream:
      bindings:
        myService-in-0:
          destination: messageprocessed
        myService-out-0:
          destination: done
      kafka:
        binder:
          enableObservation: true
          brokers: localhost:9092

  application:
    name: service-validator2


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          sleuth=DEBUG:
            # traceID and spanId are predefined MDC keys - we want the logs to include them
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8081